// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvWuUo8cfzR7pe4ueKR_nu-HQh5o7bKC0',
    appId: '1:262033054844:web:38b4ed37e5d4ec4c3c3df9',
    messagingSenderId: '262033054844',
    projectId: 'cartopia-168c0',
    authDomain: 'cartopia-168c0.firebaseapp.com',
    storageBucket: 'cartopia-168c0.appspot.com',
    measurementId: 'G-JVFWJ3SNE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXeef-jTQMDD9btzF-ixfOH-haraA-JCE',
    appId: '1:262033054844:android:5c8c38e679bbb9713c3df9',
    messagingSenderId: '262033054844',
    projectId: 'cartopia-168c0',
    storageBucket: 'cartopia-168c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mqIHDfFpy9KiW44fa1NRULBJejfMQ90',
    appId: '1:262033054844:ios:62d0947a18751e5e3c3df9',
    messagingSenderId: '262033054844',
    projectId: 'cartopia-168c0',
    storageBucket: 'cartopia-168c0.appspot.com',
    androidClientId: '262033054844-28bads5qquvr7bhgmv6elqmkvtcir2v0.apps.googleusercontent.com',
    iosClientId: '262033054844-nbm8uuv6nfunh7tp1i7n1ff85qemqhhr.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mqIHDfFpy9KiW44fa1NRULBJejfMQ90',
    appId: '1:262033054844:ios:2b23b292fa00dd933c3df9',
    messagingSenderId: '262033054844',
    projectId: 'cartopia-168c0',
    storageBucket: 'cartopia-168c0.appspot.com',
    androidClientId: '262033054844-28bads5qquvr7bhgmv6elqmkvtcir2v0.apps.googleusercontent.com',
    iosClientId: '262033054844-nmgmpvst13akn2g6vlrp28lduu3i0iha.apps.googleusercontent.com',
    iosBundleId: 'com.example.eshop.RunnerTests',
  );
}
